##Build stage 1

FROM node:14.15.4-alpine as builder
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@4.0.3 -g --silent
COPY . ./
RUN npm install
RUN npm run build

## Production stage 2
FROM nginx:stable-alpine
RUN sed -i '9i\\ttry_files $uri /index.html;' /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
