##Build stage 1

FROM node:14.15.4-alpine AS builder
WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./

RUN sed -i 's|https://SCAC-apps.railwaynet.net|http://localhost|g' package.json

RUN npm ci 
RUN npm install react-scripts@4.0.3 -g --silent
COPY . ./
COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN cp .env.production.local .env.development
RUN cp .env.production.local .env.production
RUN cp .env.production.local .env
RUN npm install
RUN npm run build

## Production stage 2
FROM nginx:stable-alpine
RUN sed -i '9i\\ttry_files $uri $uri/ /ricochet-ui/index.html;' /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html/ricochet-ui
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
