##Build stage 1

FROM node:20-alpine3.18 AS builder
WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./

RUN echo 'running Dockerfile.circleci.api-test'

RUN sed -i 's/SCAC-apps.railwaynet.net/strolr.railwaynet.datasages.com/g' package.json
RUN sed -i 's/ricochet-ui/ricochet-ui-api-test/g' package.json

RUN npm ci
RUN npm install react-scripts@4.0.3 -g
COPY . ./
COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN rm .env.production.local
RUN rm .env.production.rwn
RUN rm .env.production
RUN rm .env.development

RUN cp .env.production.datasages.circleci.api-test .env.development
RUN cp .env.production.datasages.circleci.api-test .env.production
RUN cp .env.production.datasages.circleci.api-test .env
#
#
#
#
#

#RUN sed -i 's/ricochet-ui/ricochet-ui-api-test/g' src/routes/Routes.js

RUN npm install
RUN npm run build

## Production stage 2
FROM nginx:stable-alpine
RUN sed -i '9i\\ttry_files $uri $uri/ /ricochet-ui-api-test/index.html;' /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html/ricochet-ui-api-test
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
